// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int num = Integer.parseInt(args[0]), countA = 0, countB = 0;
		double ran;
		// counts how many random numbers occure
		for(int i=0; i<num; i++) {
			ran = Math.random();
			if(ran > 0.5) {
				countA++;
			}
			else {
				countB++;
			}
		}
		// prints how many greater than 0.5 and how many less or equal to 0.5
		System.out.println("> 0.5: " + countA + " times");
		System.out.println("<= 0.5: " + countB + " times");
		// check that the 
		if(countB != 0) {
			System.out.println("Ratio: " + (double) countA/countB);
		}
	}
}
